### ISSUE TITLE
[question/offtopic?] Deploying site without separate branch, how?

### ISSUE THREAD

**Issue by AvinashReddy3108** [sharadcodes/jekyll-theme-serial-programmer#10]
Usually, you need to have a `gh-pages` branch to store the generated HTML and stuff when deploying the site.
But in this repo, I can only see one branch (of the main source code) and yet the site works.. (HOW!?)

I like it (looks neat), and will really appreciate if you can share how to do it :)

**Comment by AvinashReddy3108** [comment]
Here's my fork of your repo: https://github.com/AvinashReddy3108/me

**Comment by sharadcodes** [comment]
Just go to Pages in the repository settings and you'll get an option to set the branch for Github Pages, there you have to choose main/master branch.

 That's it

**Comment by sharadcodes** [comment]
Please close the issue if it it works for you otherwise I'm here to help, although I may not reply immediately @AvinashReddy3108
